### ISSUE TITLE
Create CCI Flows to wrap snowfakery

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#24]
Getting at SFDO-Community-Sprints/DataGenerationToolkit#109, it seems that a CCI flow would be one way to make data generation make a bit more sense.

## Problem Definition

Currently, every recipe has something that looks like
``` 
To run this file, use a command such as the following:

# cci task run generate_and_load_from_yaml -o generator_yaml ../Snowfakery-new/examples/npsp/OpportunityWithAllocations.yml -o num_records 1 -o num_records_tablename Account --org qa
```
This is tricky because our repo structure is changing pretty frequently at this point, and there are a lot of extra words going on. **New users may struggle to figure out how to modify the commands to fit their needs.**

## Desired Future State
As a VSCode user, I can run simpler commands through cci to generate Snowfakery data.
Examples:
```
cci task run snowfakery npsp/OpportunityWithAllocations.yml 
# snowfakery is the task, with a default path to get to the snowfakery recipes

cci flow run npsp_scratch_snowfakery --org dev 
# a flow to install NPSP and generate data in it 
```

**Comment by eehjunggnujhee** [comment]
Hi @allisonletts 
I actually have a similar custom flow for my personal project. The one mind-boggling issue is we will have to create a custom flow per recipe file in order to isolate the testing. We can perhaps bundle up the custom flows by the recipe folder if the automated testing for the entire collection of recipes is the goal. I hope I understood what you are iaming for.

You will be able to control the order of executions and the continuous flow of the out-of-box commands with your own custom one by creating custom tasks for them. like this.


```
    # connect cci orgs
    connect_cci_dev:
        description: Partial sandbox.
        class_path: cumulusci.tasks.command.Command
        options:
            command: cci org connect --org dev --sandbox
    connect_cci_feature:
        description: Development testing sandbox
        class_path: cumulusci.tasks.command.Command
        options:
            command: cci org connect --org feature --sandbox  
    connect_cci_release:
        description: Deployment testing sandbox.
        class_path: cumulusci.tasks.command.Command
        options:
            command: cci org connect --org release --sandbox 
```

This is a sample flow process I have using persistent org.
```
# 2 Workflow tasks collection
    # Prerequite step
    refresh_org_connections:
        group: Custom Org Connections
        description: reauthorize and reconnect cci and sfdx org connections
        steps:
            1:
                task: remove_existing_cci_dev 
            2:
                task: remove_existing_cci_feature
            3: 
                task: remove_existing_cci_release
            4:
                task: dx_authorize_dev
            5:
                task: dx_authorize_feature
            6:
                task: dx_authorize_release
            7:
                task: connect_cci_dev
            8:
                task: connect_cci_feature
            9:
                task: connect_cci_release
    # Extract dev and Load feature
    extract_and_load:
        group: ETL
        description: extract mapping from dev and load sample.sql to feature
        steps:
            1:
                task: extract_dataset_dev
            2:
                task: load_dataset_feature
    load_mock_dataset:
        group: Snowfakery recipes
        description: run SFDO snowfakery recipes
        steps:
            1:
                task: generate_opp_individual_data
            2:
                task: generate_opp_organization_data
            3:
                task: generate_opp_grant_data
```

**Comment by eehjunggnujhee** [comment]
Oh @allisonletts  I am glad that was what you were looking for. You can find descriptions and cci classes for tasks from here.
https://cumulusci.readthedocs.io/en/stable/tasks.html

Here are the custom task definitions
```
 generate_opp_individual_data:
        description: Deploy Household Opportunities
        group: SFDO Mock Data
        class_path: 
            cumulusci.tasks.bulkdata.generate_and_load_data_from_yaml.GenerateAndLoadDataFromYaml
        options:
            generator_yaml: recipes\Opportunity_npsp_Individual.recipe.yml
            num_records: 10
            num_records_tablename: Opportunity
    generate_opp_organization_data:
        description: Deploy Organization Opportunities
        group: SFDO Mock Data
        class_path: 
            cumulusci.tasks.bulkdata.generate_and_load_data_from_yaml.GenerateAndLoadDataFromYaml
        options:
            generator_yaml: recipes\Opportunity_npsp_organization.recipe.yml
            num_records: 10
            num_records_tablename: Opportunity
```

**Comment by eehjunggnujhee** [comment]
Hi @allisonletts 
If you don't mind, let's collaborate on this issue. It seems there will be multiple applications to the ourcome of this issue.

The [init file from the Snowfakery repo](https://github.com/SFDO-Tooling/Snowfakery/blob/main/cumulusci.yml) is a good example to learn how flows and tasks are organized and referencing within the file.

We have five folders in `snowfakery_samples` folder. We can have five custom flows, and each flow contains a set of custom `generate_and_load_from_yaml` tasks.

This is an example flow for PMM folder

```
sources:
    pmm:
        github: https://github.com/SalesforceFoundation/PMM

tasks:
    load_pmm_data_all:
        class_path: cumulusci.tasks.bulkdata.generate_and_load_data_from_yaml.GenerateAndLoadDataFromYaml
        options:
            generator_yaml: snowfakery_samples/PMM/pmm_1_program-service.recipe.yml
            num_records: 10
            num_records_tablename: pmdm__Program__c

flows:
    pmm_load_test:
        steps:
            1: 
                flow: pmm:install_prod
            2:
                task: load_pmm_data_all
```

@acrosman @prescod We probably need the naming convention for custom flows and tasks. Let us know what is the best way to put these together that we can use them in robot framework, Github actions, or any others that we have not discussed.
